In [9]:
from tradingview_screener import Query, col
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from adjustText import adjust_text  # Prevent overlapping labels
import seaborn as sns
import datetime
import pytz
import pygsheets

In [10]:
# Build the query
query=(Query()
 .select(
     'name',
     'close',
     'basic_eps_net_income',
     'ebitda_fy',
     'Perf.5Y',
     'last_annual_revenue',
     'price_book_ratio',
     'enterprise_value_current',
     'average_volume_30d_calc',
     'enterprise_value_ebitda_ttm',
     'dividends_yield_current'
 )
 .limit(200)
 .set_markets('nigeria')
 .set_property('symbols', {'query': {'types': ['stock', 'dr', 'fund']}})
 )

In [11]:
#help(Query)

In [12]:
# Fetch stock data from NGX
data = query.get_scanner_data()

# Extract the actual DataFrame
if isinstance(data, tuple) and len(data) == 2:
    stock_df2 = data[1]  # Extract DataFrame

    # Check if it's empty
    if not stock_df2.empty:
        print("✅ NGX Stock Data Retrieved Successfully!")
        print(stock_df2)
    else:
        print("❌ No data found for NGX stocks.")
else:
    print("❌ Unexpected data format received.")

✅ NGX Stock Data Retrieved Successfully!
               ticker        name     close  basic_eps_net_income  \
0        NSENG:SEPLAT      SEPLAT  16000.10            421.875474
1        NSENG:ARADEL      ARADEL   1530.00            173.616900
2    NSENG:ZENITHBANK  ZENITHBANK    135.40             25.316500
3          NSENG:GTCO        GTCO    137.00             25.429300
4          NSENG:MTNN        MTNN    863.00             53.068500
..                ...         ...       ...                   ...
137   NSENG:AFRINSURE   AFRINSURE      0.20                   NaN
138   NSENG:AFROMEDIA   AFROMEDIA      0.24                   NaN
139   NSENG:MULTITREX   MULTITREX      0.36             -0.075600
140   NSENG:PHARMDEKO   PHARMDEKO      1.83                   NaN
141     NSENG:EKOCORP     EKOCORP      5.80                   NaN

        ebitda_fy      Perf.5Y  last_annual_revenue  price_book_ratio  \
0    1.937873e+12  2153.535211         4.260676e+12          3.430621
1    2.977136e+11    97.955751         6.994307e+11          4.460595
2             NaN   481.899446         4.028812e+12          1.130160
3             NaN   397.277695         2.155633e+12          1.482507
4    2.751498e+12   393.142857         5.202957e+12         32.981253
..            ...          ...                  ...               ...
137           NaN     0.000000                  NaN               NaN
138           NaN    20.000000                  NaN               NaN
139 -1.343310e+08     0.000000         4.790000e+07          0.225620
140           NaN    -8.040201                  NaN               NaN
141           NaN     0.172712                  NaN               NaN

     enterprise_value_current  average_volume_30d_calc  \
0                9.895085e+12             2.141549e+05
1                7.382788e+12             2.393251e+06
2               -6.394660e+11             2.844219e+07
3                1.381247e+12             2.448075e+07
4                1.996464e+13             3.497351e+06
..                        ...                      ...
137                       NaN             0.000000e+00
138                       NaN             0.000000e+00
139                       NaN             0.000000e+00
140                       NaN             0.000000e+00
141                       NaN             0.000000e+00

     enterprise_value_ebitda_ttm  dividends_yield_current
0                       4.406008                 1.718633
1                       4.361907                 2.156863
2                            NaN                 3.891772
3                            NaN                 5.861314
4                       6.193391                 0.000000
..                           ...                      ...
137                          NaN                 0.000000
138                          NaN                 0.000000
139                          NaN                 0.000000
140                          NaN                 0.000000
141                          NaN                      NaN

[142 rows x 12 columns]

In [13]:
# Correct file path (use double backslashes `\\` or raw string `r""`)
file_path = r"C:\Users\Segun\Desktop\Us Stocks Data.xlsx"

# Save the DataFrame to an Excel file
stock_df2.to_excel(file_path, index=False)

# Print confirmation message
print(f"File saved successfully: {file_path}")

File saved successfully: C:\Users\Segun\Desktop\Us Stocks Data.xlsx

In [14]:
stock_df2 = pd.read_excel(r"C:\Users\Segun\Desktop\Us Stocks Data.xlsx")
stock_df2 = stock_df2.drop('ticker', axis=1)
stock_df2

,name,close,basic_eps_net_income,ebitda_fy,Perf.5Y,last_annual_revenue,price_book_ratio,enterprise_value_current,average_volume_30d_calc,enterprise_value_ebitda_ttm,dividends_yield_current
0,SEPLAT,16000.10,421.875474,1.937873e+12,2153.535211,4.260676e+12,3.430621,9.895085e+12,2.141549e+05,4.406008,1.718633
1,ARADEL,1530.00,173.616900,2.977136e+11,97.955751,6.994307e+11,4.460595,7.382788e+12,2.393251e+06,4.361907,2.156863
2,ZENITHBANK,135.40,25.316500,NaN,481.899446,4.028812e+12,1.130160,-6.394660e+11,2.844219e+07,NaN,3.891772
3,GTCO,137.00,25.429300,NaN,397.277695,2.155633e+12,1.482507,1.381247e+12,2.448075e+07,NaN,5.861314
4,MTNN,863.00,53.068500,2.751498e+12,393.142857,5.202957e+12,32.981253,1.996464e+13,3.497351e+06,6.193391,0.000000
...,...,...,...,...,...,...,...,...,...,...,...
137,AFRINSURE,0.20,NaN,NaN,0.000000,NaN,NaN,NaN,0.000000e+00,NaN,0.000000
138,AFROMEDIA,0.24,NaN,NaN,20.000000,NaN,NaN,NaN,0.000000e+00,NaN,0.000000
139,MULTITREX,0.36,-0.075600,-1.343310e+08,0.000000,4.790000e+07,0.225620,NaN,0.000000e+00,NaN,0.000000
140,PHARMDEKO,1.83,NaN,NaN,-8.040201,NaN,NaN,NaN,0.000000e+00,NaN,0.000000
141,EKOCORP,5.80,NaN,NaN,0.172712,NaN,NaN,NaN,0.000000e+00,NaN,NaN

In [15]:
# Authorize with service account
gc = pygsheets.authorize(service_account_file=r"C:\Users\Segun\Desktop\wqu-satellite-image-learning1-175e0a0906aa.json")

# Open the spreadsheet by URL
sh = gc.open_by_url("https://docs.google.com/spreadsheets/d/1jkbrrHnR48JztVz0SrqZELKjOenVm44wsiIchLW0K9g/edit#gid=1868316212")

# Select the 5th worksheet (index 4)
wks = sh[0]

# Push DataFrame starting at cell A1
wks.set_dataframe(stock_df2, (1,1))

In [16]:
stock_df2.tail(14)

,name,close,basic_eps_net_income,ebitda_fy,Perf.5Y,last_annual_revenue,price_book_ratio,enterprise_value_current,average_volume_30d_calc,enterprise_value_ebitda_ttm,dividends_yield_current
128,NNFM,79.40,0.1437,364963000.0,892.500000,2.154733e+10,1.165305,1.336246e+10,5034.700000,NaN,0.944584
129,LIVINGTRUST,2.60,0.0463,NaN,288.059701,6.666724e+09,2.464221,1.341431e+10,284685.166667,NaN,3.076923
130,INFINITY,11.25,0.3238,NaN,1604.545455,6.791968e+09,7.968269,1.213184e+11,21844.200000,NaN,1.555556
131,MORISON,10.40,0.0098,-20567000.0,395.238095,5.137670e+08,10.936547,1.310061e+10,14616.200000,NaN,0.000000
132,ENAMELWA,40.70,-1.0536,-40874000.0,151.234552,1.301835e+09,-3.825659,2.535895e+09,1137.466667,62.870839,0.000000
133,MOFIREIF,100.00,NaN,NaN,0.000000,NaN,NaN,NaN,360.300000,NaN,NaN
134,STACO,0.48,NaN,NaN,0.000000,NaN,NaN,NaN,0.000000,NaN,0.000000
135,GOLDBREW,7.10,NaN,NaN,776.543210,NaN,NaN,NaN,0.000000,NaN,0.000000
136,UNITYBNK,1.51,NaN,NaN,174.545455,NaN,NaN,NaN,0.000000,NaN,0.000000
137,AFRINSURE,0.20,NaN,NaN,0.000000,NaN,NaN,NaN,0.000000,NaN,0.000000
138,AFROMEDIA,0.24,NaN,NaN,20.000000,NaN,NaN,NaN,0.000000,NaN,0.000000
139,MULTITREX,0.36,-0.0756,-134331000.0,0.000000,4.790000e+07,0.225620,NaN,0.000000,NaN,0.000000
140,PHARMDEKO,1.83,NaN,NaN,-8.040201,NaN,NaN,NaN,0.000000,NaN,0.000000
141,EKOCORP,5.80,NaN,NaN,0.172712,NaN,NaN,NaN,0.000000,NaN,NaN